language: cpp

sudo: required
dist: trusty

cache: ccache

matrix:
  include:
    - env: VERSION=6 BITS=32
      compiler: gcc-6-32
      os: linux
    - env: VERSION=5 BITS=32
      compiler: gcc-5-32
      os: linux
    - env: VERSION=4.9 BITS=32
      compiler: gcc-4.9-32
      os: linux
    - env: VERSION=3.7 BITS=32
      compiler: clang-3.7-32
      os: linux
    - env: VERSION=4.9 BITS=64
      compiler: gcc-4.9-64
      os: linux

before_install:
  - ./travis.sh before_install

script:
  - ./travis.sh script

after_success:
  - ./travis.sh after_success
