name: ðŸŒŽ Update Base Translation

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 12am UTC.
  workflow_dispatch: # As well as manually.

jobs:
  update:
    if: github.repository == 'PCSX2/pcsx2'
    name: "Update Base Translation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Update Base Translation
        run: ./.github/workflows/scripts/common/update_base_translation.sh
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725
        with:
          title: "Qt: Update Base Translation"
          commit-message: "[ci skip] Qt: Update Base Translation."
          committer: "PCSX2 Bot <PCSX2Bot@users.noreply.github.com>"
          author: "PCSX2 Bot <PCSX2Bot@users.noreply.github.com>"
          body: "Daily update of base translation sources."
          branch: update-base-translation
          delete-branch: true
