name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build csharp
      run: |
        docker build ./c# -t aimvector/csharp:1.0.0
    - name: docker build nodejs
      run: |
        docker build ./nodejs -t aimvector/nodejs:1.0.0
    - name: docker build python
      run: |
        docker build ./python -t aimvector/python:1.0.0
    - name: docker build golang
      run: |
        docker build ./golang -t aimvector/golang:1.0.0
    - name: docker push
      run: |
        docker push aimvector/csharp:1.0.0
        docker push aimvector/nodejs:1.0.0
        docker push aimvector/golang:1.0.0
        docker push aimvector/python:1.0.0