name: üìù Validate GameDB

on:
  push:
    branches:
      - master
    paths:
      - '**/GameIndex.yaml'
  pull_request:
    branches:
      - master
    paths:
      - '**/GameIndex.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate GameDB
        env:
          SCRIPT_DIR: .github/workflows/scripts/validation/lint-gamedb
        run: |
          pip install -r "${SCRIPT_DIR}/requirements.txt"
          python "${SCRIPT_DIR}/lint-gamedb.py"
