name: üñ•Ô∏è Windows Builds

on:
  push:
    branches-ignore:
      - "l10n_master"
  pull_request:
    branches:
      - master

jobs:
  # MSBUILD
  lint_vs_proj_files:
    name: Lint VS Project Files
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    runs-on: windows-2025
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Verify VS Project Files
        run: .github\workflows\scripts\windows\validate-vs-filters.ps1

  build_qt_sse4:
    needs: lint_vs_proj_files
    name: "SSE4"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: "MSVC SSE4"
      artifactPrefixName: "PCSX2-windows-Qt-x64-sse4-msvc"
      configuration: Release
      simd: "SSE4"
    secrets: inherit

  build_qt_avx2:
    needs: lint_vs_proj_files
    name: "AVX2"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: "MSVC AVX2"
      artifactPrefixName: "PCSX2-windows-Qt-x64-avx2-msvc"
      configuration: Release AVX2
    secrets: inherit

  build_qt_cmake:
    name: "CMake"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: "CMake MSVC"
      artifactPrefixName: "PCSX2-windows-Qt-x64-cmake-msvc"
      configuration: CMake
      buildSystem: cmake
    secrets: inherit

  build_qt_clang_sse4:
    needs: lint_vs_proj_files
    name: "SSE4"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: "Clang SSE4"
      artifactPrefixName: "PCSX2-windows-Qt-x64-sse4-clang"
      configuration: Release Clang
      simd: "SSE4"
    secrets: inherit

  build_qt_clang_avx2:
    needs: lint_vs_proj_files
    name: "AVX2"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: "Clang AVX2"
      artifactPrefixName: "PCSX2-windows-Qt-x64-avx2-clang"
      configuration: Release Clang AVX2
    secrets: inherit

  build_qt_cmake_clang:
    name: "CMake"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: "CMake Clang"
      artifactPrefixName: "PCSX2-windows-Qt-x64-cmake-clang"
      configuration: CMake
      buildSystem: cmake
      cmakeFlags: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DPCSX2_EXE_NAME=pcsx2-qt-clang
    secrets: inherit
